package com.softwaremagico.librodeesher.profession;

import com.softwaremagico.librodeesher.exceptions.InvalidXmlElementException;
import com.softwaremagico.librodeesher.magic.RealmOfMagic;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Verifies {@link ProfessionFactory} against the real {@code profesiones.xml} files generated by
 * {@link com.softwaremagico.librodeesher.migration.ProfessionMigrationTool} from the legacy
 * "LibroDeEsher" data, with every module enabled (the default).
 */
@Test(groups = "professionFactory")
public class ProfessionFactoryTest {

    @Test
    public void readsProfessionsFromEveryEnabledModule() throws InvalidXmlElementException {
        // 42 profession files across 11 modules, but "Monje" is defined by both "ArtesMarciales" and
        // "ManualPersonajes": the module enabled later wins (see XmlFactory), so only 41 unique ids
        // remain visible.
        Assert.assertEquals(ProfessionFactory.getInstance().getElements().size(), 41);
    }

    @Test
    public void wizardHasSpellCastingRealmsAndBonuses() throws InvalidXmlElementException {
        final Profession mago = ProfessionFactory.getInstance().getElement("wizard");

        Assert.assertTrue(mago.isSpellCaster());
        Assert.assertEquals(mago.getMagicRealms(), java.util.List.of(RealmOfMagic.ESSENCE));
        Assert.assertFalse(mago.isIndifferentToCharacteristics());
        Assert.assertFalse(mago.getBonuses().isEmpty());
        Assert.assertFalse(mago.getMagicCostsRaw().isBlank());
    }

    @Test(expectedExceptions = InvalidXmlElementException.class)
    public void unknownProfessionIdThrows() throws InvalidXmlElementException {
        ProfessionFactory.getInstance().getElement("does-not-exist");
    }
}
