package com.softwaremagico.librodeesher.skill;

import com.softwaremagico.librodeesher.exceptions.InvalidXmlElementException;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Verifies {@link SkillFactory} against the real {@code habilidades.xml} files generated by
 * {@link com.softwaremagico.librodeesher.migration.SkillMigrationTool} from the legacy
 * "LibroDeEsher" data, with every module enabled (the default).
 */
@Test(groups = "skillFactory")
public class SkillFactoryTest {

    @Test
    public void readsSkillsFromEveryEnabledModule() throws InvalidXmlElementException {
        // At least one skill from each module that contributes habilidades.xml (Basico, Pulp,
        // ArtesMarciales, RazasYCulturas, NoOficiales, ArmasDeFuego, FuegoYHielo, Esencia).
        Assert.assertTrue(SkillFactory.getInstance().getElements().size() > 400);
    }

    @Test
    public void martialArtsStyleCarriesItsChiPowerEnableSkills() throws InvalidXmlElementException {
        final Skill estiloDeLaGrulla = SkillFactory.getInstance().getElement("Estilo de la Grulla");

        Assert.assertEquals(estiloDeLaGrulla.getCategoryId(), "Artes Marciales·Maniobras de Combate");
        Assert.assertEquals(estiloDeLaGrulla.getEnableSkills(),
                java.util.List.of("Poderes Chi: Ataque Sin Sombra", "Poderes Chi: Golpes Contínuos"));
        Assert.assertFalse(estiloDeLaGrulla.isAllEnabled(), "'|' separated enable-skills are OR, not AND");
    }

    @Test
    public void chiPowerGrantedByAStyleStartsDisabled() throws InvalidXmlElementException {
        // "Poderes Chi: Ataque Sin Sombra" is only usable once a martial arts style that grants it
        // (e.g. "Estilo de la Grulla") has been learned.
        final Skill chiPower = SkillFactory.getInstance().getElement("Poderes Chi: Ataque Sin Sombra");

        Assert.assertFalse(chiPower.isEnabledByDefault());
        Assert.assertEquals(chiPower.getSkillGroup(), SkillGroup.CHI);
    }

    @Test
    public void rareSkillIsFlagged() throws InvalidXmlElementException {
        final Skill xenoKnowledge = SkillFactory.getInstance().getElement("Xeno-Conocimientos");

        Assert.assertTrue(xenoKnowledge.isRare());
    }

    @Test(expectedExceptions = InvalidXmlElementException.class)
    public void unknownSkillIdThrows() throws InvalidXmlElementException {
        SkillFactory.getInstance().getElement("does-not-exist");
    }
}
