package com.softwaremagico.librodeesher.perk;

import com.softwaremagico.librodeesher.exceptions.InvalidXmlElementException;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Verifies {@link PerkFactory} against the real {@code talentos.xml} files generated by
 * {@link com.softwaremagico.librodeesher.migration.PerkMigrationTool} from the legacy
 * "LibroDeEsher" data, with every module enabled (the default).
 */
@Test(groups = "perkFactory")
public class PerkFactoryTest {

    @Test
    public void readsPerksFromEveryEnabledModule() throws InvalidXmlElementException {
        // 147 (ManualPersonajes) + 2 (RazasSubterraneas) + 1 (NoOficiales).
        Assert.assertEquals(PerkFactory.getInstance().getElements().size(), 150);
    }

    @Test
    public void weaknessHasANegativeCost() throws InvalidXmlElementException {
        final Perk addiction = PerkFactory.getInstance().getElement("Adicción Ligera");

        Assert.assertTrue(addiction.isWeakness());
        Assert.assertEquals(addiction.getCost(), Integer.valueOf(-20));
        Assert.assertEquals(addiction.getType(), PerkType.MENTAL);
    }

    @Test
    public void swappedGradeAndTypeColumnsFallBackLikeTheLegacyParser() throws InvalidXmlElementException {
        // Real data typo in "ManualPersonajes": the "Grado" column contains "Mental" (a PerkType tag)
        // and the "Tipo" column contains "Máximo" (a PerkGrade tag). The legacy parser silently
        // defaulted both to MAXIMUM/OTHER instead of failing; this is reproduced on purpose.
        final Perk promise = PerkFactory.getInstance().getElement("Promesa (Máximo)");

        Assert.assertEquals(promise.getGrade(), PerkGrade.MAXIMUM);
        Assert.assertEquals(promise.getType(), PerkType.OTHER);
    }

    @Test
    public void raceRestrictedPerkIsNotAvailableToEveryone() throws InvalidXmlElementException {
        final Perk ansioso = PerkFactory.getInstance().getElement("Ansioso");

        Assert.assertFalse(ansioso.isAvailableToEveryone());
        Assert.assertEquals(ansioso.getAvailableTo(), java.util.List.of("Orco Gris"));
    }

    @Test(expectedExceptions = InvalidXmlElementException.class)
    public void unknownPerkIdThrows() throws InvalidXmlElementException {
        PerkFactory.getInstance().getElement("does-not-exist");
    }
}
