package com.softwaremagico.librodeesher.weapon;

import com.softwaremagico.librodeesher.exceptions.InvalidXmlElementException;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Verifies {@link WeaponFactory} against the real {@code armas.xml} files generated by
 * {@link com.softwaremagico.librodeesher.migration.WeaponMigrationTool} from the legacy
 * "LibroDeEsher" data, with every module enabled (the default).
 */
@Test(groups = "weaponFactory")
public class WeaponFactoryTest {

    @Test
    public void readsWeaponsFromEveryEnabledModule() throws InvalidXmlElementException {
        Assert.assertTrue(WeaponFactory.getInstance().getElements().size() > 150);
    }

    @Test
    public void daggerBelongsToTheEdgeCategory() throws InvalidXmlElementException {
        final Weapon dagger = WeaponFactory.getInstance().getElement("dagger");

        Assert.assertEquals(dagger.getType(), WeaponType.EDGE);
        Assert.assertEquals(dagger.getCategoryId(), "weaponsEdged");
        Assert.assertFalse(dagger.isRare());
    }

    @Test
    public void getWeaponsByTypeOnlyReturnsThatType() throws InvalidXmlElementException {
        for (final Weapon weapon : WeaponFactory.getInstance().getWeaponsByType(WeaponType.HANDLE)) {
            Assert.assertEquals(weapon.getType(), WeaponType.HANDLE);
        }
    }

    @Test(expectedExceptions = InvalidXmlElementException.class)
    public void unknownWeaponIdThrows() throws InvalidXmlElementException {
        WeaponFactory.getInstance().getElement("does-not-exist");
    }
}
