package com.softwaremagico.librodeesher.training;

import com.softwaremagico.librodeesher.exceptions.InvalidXmlElementException;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Verifies {@link TrainingFactory} against the real {@code adiestramientos.xml} files generated by
 * {@link com.softwaremagico.librodeesher.migration.TrainingMigrationTool} from the legacy
 * "LibroDeEsher" data, with every module enabled (the default).
 */
@Test(groups = "trainingFactory")
public class TrainingFactoryTest {

    @Test
    public void readsTrainingsFromEveryEnabledModule() throws InvalidXmlElementException {
        // 2+15+3+1+21+2+5+2 = 51 training files across the 8 contributing modules.
        Assert.assertEquals(TrainingFactory.getInstance().getElements().size(), 51);
    }

    @Test
    public void soldierTrainingHasExpectedFields() throws InvalidXmlElementException {
        final Training soldier = TrainingFactory.getInstance().getElement("soldier");

        Assert.assertEquals(soldier.getTrainingTimeInMonths(), Integer.valueOf(26));
        Assert.assertTrue(soldier.isAvailableToEveryRace());
        Assert.assertFalse(soldier.getSpecialItems().isEmpty());
        Assert.assertFalse(soldier.getCategories().isEmpty());
        Assert.assertTrue(soldier.getCharacteristicUpgrades().isEmpty());
        Assert.assertTrue(soldier.getRequirements().isEmpty());
    }

    @Test
    public void soldierTrainingGrantsLightArmorCategoryRanks() throws InvalidXmlElementException {
        final Training soldier = TrainingFactory.getInstance().getElement("soldier");

        final TrainingCategoryGrant lightArmor = soldier.getCategories().stream()
                .filter(grant -> grant.getCategoryOptions().contains("armorLight"))
                .findFirst().orElseThrow();

        Assert.assertFalse(lightArmor.isChoice());
        Assert.assertEquals(lightArmor.getRanksGranted(), Integer.valueOf(2));
        Assert.assertEquals(lightArmor.getMinSkills(), Integer.valueOf(1));
        Assert.assertEquals(lightArmor.getMaxSkills(), Integer.valueOf(1));
        Assert.assertEquals(lightArmor.getRanksToDistribute(), Integer.valueOf(2));
    }

    @Test
    public void soldierTrainingOffersAChoiceOfWeaponCategories() throws InvalidXmlElementException {
        final Training soldier = TrainingFactory.getInstance().getElement("soldier");

        final TrainingCategoryGrant weaponChoice = soldier.getCategories().stream()
                .filter(TrainingCategoryGrant::isChoice)
                .findFirst().orElseThrow();

        Assert.assertTrue(weaponChoice.getCategoryOptions().size() > 1);
        Assert.assertTrue(weaponChoice.getCategoryOptions().stream().allMatch(option -> option.startsWith("weapons")));
    }

    @Test(expectedExceptions = InvalidXmlElementException.class)
    public void unknownTrainingIdThrows() throws InvalidXmlElementException {
        TrainingFactory.getInstance().getElement("does-not-exist");
    }
}
