package com.softwaremagico.librodeesher.category;

import com.softwaremagico.librodeesher.exceptions.InvalidXmlElementException;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.util.List;

/**
 * Verifies {@link CategoryFactory} against the real {@code categorias.xml} files generated by
 * {@link com.softwaremagico.librodeesher.migration.CategoryMigrationTool} from the legacy
 * "LibroDeEsher" data, with every module enabled (the default).
 */
@Test(groups = "categoryFactory")
public class CategoryFactoryTest {

    @Test
    public void readsEveryCategoryFromEveryEnabledModule() throws InvalidXmlElementException {
        final List<Category> categories = CategoryFactory.getInstance().getElements();

        // 62 categories first defined in "Basico" (which also carries the always-active base file)
        // plus 3 new ones introduced by "Pulp": see CategoryMigrationTool's javadoc for why other
        // modules that only add skills to an existing category do not contribute new entries here.
        Assert.assertEquals(categories.size(), 65);
    }

    @Test
    public void lightArmorCategoryHasExpectedFields() throws InvalidXmlElementException {
        final Category lightArmor = CategoryFactory.getInstance().getElement("armorLight");

        Assert.assertEquals(lightArmor.getAbbreviation(), "ArdL");
        Assert.assertEquals(lightArmor.getCharacteristics(), List.of("Ag", "Fu", "Ag"));
        Assert.assertEquals(lightArmor.getType(), CategoryType.STANDARD);
        Assert.assertTrue(lightArmor.getSkills().contains("Cuero Endurecido"));
        Assert.assertTrue(lightArmor.getSkills().contains("Cuero Blando"));
    }

    @Test
    public void weaponCategoriesHaveDynamicSkills() throws InvalidXmlElementException {
        final Category twoHandedWeapons = CategoryFactory.getInstance().getElement("weaponsTwoHanded");

        Assert.assertTrue(twoHandedWeapons.hasDynamicSkills(),
                "weapon categories list their skills in the weapon files, not in categorias.txt");
        Assert.assertTrue(twoHandedWeapons.getSkills().isEmpty());
    }

    @Test(expectedExceptions = InvalidXmlElementException.class)
    public void unknownCategoryIdThrows() throws InvalidXmlElementException {
        CategoryFactory.getInstance().getElement("does-not-exist");
    }
}
