package com.softwaremagico.librodeesher.magic;

import com.softwaremagico.librodeesher.exceptions.InvalidXmlElementException;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Verifies {@link MagicSpellListFactory} against the real {@code hechizos.xml} files generated by
 * {@link com.softwaremagico.librodeesher.migration.MagicMigrationTool} from the legacy
 * "LibroDeEsher" data, with every module enabled (the default).
 */
@Test(groups = "magicSpellListFactory")
public class MagicSpellListFactoryTest {

    @Test
    public void readsSpellListsFromEveryEnabledModule() throws InvalidXmlElementException {
        Assert.assertTrue(MagicSpellListFactory.getInstance().getElements().size() > 300);
    }

    @Test
    public void spellListHasRealmQualifiedId() throws InvalidXmlElementException {
        final MagicSpellList fireLaw = MagicSpellListFactory.getInstance()
                .getElement(MagicSpellList.buildId(RealmOfMagic.ESSENCE, "Ley del Fuego"));

        Assert.assertEquals(fireLaw.getRealm(), RealmOfMagic.ESSENCE);
        Assert.assertTrue(fireLaw.getOwners().contains("Mago"));
    }

    @Test
    public void openAndClosedListsAreRecognized() throws InvalidXmlElementException {
        final MagicSpellList openList = MagicSpellListFactory.getInstance()
                .getElement(MagicSpellList.buildId(RealmOfMagic.ESSENCE, "Barrera Contra Hechizos"));
        Assert.assertTrue(openList.isOpenList());

        final MagicSpellList closedList = MagicSpellListFactory.getInstance()
                .getElement(MagicSpellList.buildId(RealmOfMagic.ESSENCE, "Bridas de los Hechizos"));
        Assert.assertTrue(closedList.isClosedList());
    }

    @Test
    public void getSpellListsFiltersByRealm() throws InvalidXmlElementException {
        for (final MagicSpellList list : MagicSpellListFactory.getInstance().getSpellLists(RealmOfMagic.RACE)) {
            Assert.assertEquals(list.getRealm(), RealmOfMagic.RACE);
        }
    }

    @Test(expectedExceptions = InvalidXmlElementException.class)
    public void unknownSpellListIdThrows() throws InvalidXmlElementException {
        MagicSpellListFactory.getInstance().getElement("does-not-exist");
    }
}
